language: node_js
node_js: stable

cache:
  yarn: false
  directories:
    - node_modules

script:
  - yarn build

after_success:
  - cd ./public
  - git init
  - git config user.name "ntnyq"
  - git config user.email "ntnyq13@gmail.com"
  - git add .
  - git commit -m ":rocket:Update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
  - scp -r ./* ntnyq@47.52.31.173:/home/ntnyq/web/palette

branches:
  only:
    - master
env:
  global:
    - GH_REF: github.com/ntnyq/yui-palette.git

addons:
  ssh_known_hosts: 47.52.31.173

before_install:
  - openssl aes-256-cbc -K $encrypted_8939d479ba24_key -iv $encrypted_8939d479ba24_iv
    -in id_rsa_deploy.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
